@startuml
'https://plantuml.com/sequence-diagram
!theme toy

autonumber
'签约用的图片上传
充电平台 -> 银联: 调用3.1接口，上传签约相关的图片
activate 银联
银联 --> 充电平台: 返回图片路径、类型、大小
deactivate 银联

'详细信息上传
充电平台 -> 银联: 调用3.2接口，上传详细信息（携带图片信息）
activate 银联
银联 --> 充电平台: 返回自助签约平台流水号
deactivate 银联

'签约协议
充电平台 -> 银联: 前端携带自助签约平台流水号，调用3.3接口，打开协议签约页面，用户完成协议签约

'入网状态查询
充电平台 -> 银联: 携带自助签约平台流水号，调用3.4接口，查询入网状态
activate 银联
银联 --> 充电平台: 返回申请状态
deactivate 银联

@enduml
