@startuml
'https://plantuml.com/sequence-diagram
!theme toy

xxljob -> 清分服务: 调用回盘定时任务
activate 清分服务
清分服务 -> 清分服务: 查询所有进行中的核销明细的回盘文件名称
清分服务 -> 清分服务: 从ftp读取回盘文件，并解析文件内容，转成可读的核销结果数据
清分服务 -> 清分服务: 调整核销明细的核销结果
清分服务 -> 清分服务: 调整关联清分订单的清分状态
清分服务 -> 清分服务: 数据入库
清分服务 -> 清分服务: 新增清分流水和清分钱包金额
@enduml
