@startuml
'https://plantuml.com/sequence-diagram
!theme toy

xxljob -> 清分服务: 调用提交定时任务
activate 清分服务
清分服务 -> 清分服务: 查询所有待提交的核销明细
清分服务 -> 清分服务: 将核销明细转为银联指定格式，并生成核销文件
清分服务 -> 清分服务: 核销文件上传至ftp
清分服务 -> 清分服务: 调整核销明细关联清分订单的状态
清分服务 -> 清分服务: 数据入库
@enduml
