@startuml
'https://plantuml.com/sequence-diagram
!theme toy

xxljob -> 清分服务: 调用分账定时任务
activate 清分服务
清分服务 -> 清分服务: 查询所有待核销、无额度、扣负挂起状态的清分订单
清分服务 -> 清分服务: 批量查询清分消费明细
清分服务 -> 清分服务: 构建清分策略查询参数，批量查询清分策略
清分服务 -> 清分服务: 批量查询运营商及平台在银联对应的企业用户号
清分服务 -> 清分服务: 开始计算抽成，优先将可清分的金额划给运营商，\n分别记录运营商和平台的线上线下抽成
清分服务 -> 清分服务: 对待核销的清分订单，线上抽成生成清分订单核销明细
清分服务 -> 清分服务: 数据入库
@enduml
