@startuml
'https://plantuml.com/sequence-diagram
!theme toy

xxljob -> 清分服务: 执行分支核销定时任务
activate 清分服务
清分服务 -> 清分服务: 查询所有清分状态为未分账（有额度）、未分账（无额度）和无额度的清分订单
清分服务 -> 清分服务: 未分账（有额度）清分订单与退款记录对冲逻辑， \n生成用户额度、用户额度明细；\n修改未分账（有额度）清分订单、退款记录、清分订单消费明细；
清分服务 -> 清分服务: 未分账（无额度）清分订单与用户可用额度处理逻辑，\n生成用户额度使用记录、清分订单消费明细；\n修改未分账（无额度）清分订单、用户额度、用户额度明细；
@enduml
