@startuml
'https://plantuml.com/sequence-diagram

!theme toy


group 1、停止充电
actor 充电用户
充电用户 -> 小程序: 停止充电
小程序 -> 充电服务: 调用停止充电接口
activate 充电服务
充电服务 -> 充电服务: 充电设备鉴权
充电服务 -> 桩服务: 调用停止充电接口
activate 桩服务
桩服务 -> 桩服务: 生成停止充电报文
桩服务 -> 充电桩: 下发停止充电指令
activate 充电桩
充电桩 --> 桩服务: 返回指令下发成功
deactivate 充电桩
桩服务 --> 充电服务: 返回指令下发成功
deactivate 桩服务
充电服务 -> 充电服务: 调整充电记录状态（停止中）
deactivate 充电服务
end


group 2、实时数据上送
充电桩 -> 桩服务: 上送实时数据报文
activate 桩服务
桩服务 -> 桩服务: 解析实时数据报文
桩服务 -> kafka: 发送实时数据消息
deactivate 桩服务
充电服务 -> kafka: 拉取实时数据消息
activate 充电服务
充电服务 -> 充电服务: 保存交易数据
充电服务 -> 充电服务: 从缓存中获取充电数据
充电服务 -> 充电服务: 保存充电数据
充电服务 -> 充电服务: 修改充电记录状态（已停止）
充电服务 -> kafka: 发送充电停止消息
deactivate 充电服务
end

group 3、占位订单生成
订单服务 -> kafka: 拉取充电停止消息
activate 订单服务
订单服务 -> 订单服务: 查询当前充电枪状态
订单服务 -> 订单服务: 查询充电站信息
订单服务 -> 订单服务: 查询充电记录关联的订单
订单服务 -> 订单服务: 根据充电订单和电站的占位配置\n构建占位订单
订单服务 -> 订单服务: 占位订单保存
deactivate 订单服务
end















@enduml
