@startuml
'https://plantuml.com/sequence-diagram

!theme toy

充电桩 -> 桩服务: 上送心跳数据
activate 桩服务
桩服务 -> 桩服务: 将心跳数据解析成充电状态消息
桩服务 -> kafka: 发送充电状态消息
deactivate 桩服务

充电服务 -> kafka: 拉取充电状态消息
activate 充电服务
充电服务 -> 充电服务: 如果正在充电，保存充电数据
充电服务 -> 充电服务: 比较电桩状态是否和之前相同，\n状态变位或者故障码变化，\n发送枪变位消息
充电服务 -> 充电服务: 变更充电记录状态
deactivate 充电服务

订单服务 -> kafka: 拉取枪变位消息
activate 订单服务
订单服务 -> 订单服务: 占用(未充电)->任意状态，\n占位单就结算
订单服务 -> kafka: 发送订单结算消息
deactivate 订单服务

财务服务 -> kafka: 拉取订单结算消息
activate 财务服务
财务服务 -> 财务服务: 短信配置查询
财务服务 -> 财务服务: 占位费配置查询
财务服务 -> 财务服务: 异常冻结的金额解冻
财务服务 -> 财务服务: 企业钱包、个人钱包扣款
财务服务 -> kafka: 发送钱包扣款和占位单短信通知的消息
财务服务 -> 财务服务: 生成票务订单
deactivate 财务服务
@enduml
