@startuml
'https://plantuml.com/sequence-diagram

!theme toy


group 1、启动充电
actor 充电用户
充电用户 -> 小程序: 发起充电
activate 小程序
小程序 -> 充电服务: 调用启充充电接口
activate 充电服务
充电服务 -> 充电服务: 用户信息鉴权
充电服务 -> 充电服务: 充电设备鉴权
充电服务 -> 充电服务: 生成充电记录（启动中）
充电服务 -> 桩服务: 调用启充充电接口
activate 桩服务
桩服务 -> 桩服务: 生成启动充电报文
桩服务 -> 充电桩: 下发启动充电指令
activate 充电桩
充电桩 --> 桩服务: 返回指令下发成功
deactivate 充电桩
桩服务 --> 充电服务: 返回指令下发成功
deactivate 桩服务
充电服务 -> 充电服务: 保存充电记录（启动中）
充电服务 -> kafka: 发送开始充电消息
充电服务 --> 小程序: 返回充电单号和用户余额
deactivate 充电服务
小程序 --> 充电用户: 展示120秒启动中页面
deactivate 小程序
end

group 2、实时订单生成
订单服务 -> kafka: 拉取开始充电消息
activate 订单服务
订单服务 -> 订单服务: 查询并生成当前充电桩单价
订单服务 -> 订单服务: 生成实时订单
订单服务 -> 订单服务: 保存单价和实时订单
end

group 3、启动中页面
小程序 -> 充电服务: 轮询充电记录状态
activate 小程序
activate 充电服务
充电服务 --> 小程序: 返回充电记录状态
小程序 --> 充电用户: 充电记录状态为充电中，\n展示充电中页面，否则继续轮询
deactivate 小程序
deactivate 充电服务
end

group 4、启充结果上送
充电桩 -> 桩服务: 上送启动充电响应报文
activate 桩服务
桩服务 -> 桩服务: 解析启充充电响应报文
桩服务 -> kafka: 发送启动充电结果消息
deactivate 桩服务
充电服务 -> kafka: 拉取启动充电结果消息
activate 充电服务
充电服务 -> 充电服务: 修改充电记录状态（启动中 -> 充电中）
deactivate 充电服务

end








@enduml
