@startuml
'https://plantuml.com/sequence-diagram

!theme toy


group 1、停止充电
actor 充电用户
充电用户 -> 小程序: 停止充电
小程序 -> 充电服务: 调用停止充电接口
activate 充电服务
充电服务 -> 充电服务: 充电设备鉴权
充电服务 -> 桩服务: 调用停止充电接口
activate 桩服务
桩服务 -> 桩服务: 生成停止充电报文
桩服务 -> 充电桩: 下发停止充电指令
activate 充电桩
充电桩 --> 桩服务: 返回指令下发成功
deactivate 充电桩
桩服务 --> 充电服务: 返回指令下发成功
deactivate 桩服务
充电服务 -> 充电服务: 调整充电记录状态（停止中）
deactivate 充电服务
end

group 2、停充结果上送
充电桩 -> 桩服务: 上送停止充电响应报文
activate 桩服务
桩服务 -> 桩服务: 解析停止充电响应报文
桩服务 -> kafka: 发送停止充电结果消息
deactivate 桩服务
充电服务 -> kafka: 拉取停止充电结果消息
activate 充电服务
充电服务 -> 充电服务: 修改充电记录状态（停止中）
deactivate 充电服务
end

group 3、实时数据上送
充电桩 -> 桩服务: 上送实时数据报文
activate 桩服务
桩服务 -> 桩服务: 解析实时数据报文
桩服务 -> kafka: 发送实时数据消息
deactivate 桩服务
充电服务 -> kafka: 拉取实时数据消息
activate 充电服务
充电服务 -> 充电服务: 保存交易数据
充电服务 -> 充电服务: 从缓存中获取充电数据
充电服务 -> 充电服务: 保存充电数据
充电服务 -> 充电服务: 修改充电记录状态（已停止）
充电服务 -> kafka: 发送充电停止消息
deactivate 充电服务
end

group 4、历史订单生成
订单服务 -> kafka: 拉取充电停止消息
activate 订单服务
订单服务 -> 订单服务: 查询实时订单或者异常订单\n（有些场景实时订单已经进入异常订单）
订单服务 -> 订单服务: 判断订单中异常原因是否为无结算数据\n是，转为异常订单，不进行后续处理
订单服务 -> 订单服务: 互联互通订单进行入口方案处理
订单服务 -> 订单服务: 根据充电原价计算订单金额、电量等数据
订单服务 -> 订单服务: 校验订单金额、电量是否异常\n如果异常，就转为异常订单，不进行后续处理
订单服务 -> 订单服务: 充电金额优惠处理（电站活动、权益优惠、流量方案、抹零等）
订单服务 -> 订单服务: 优惠券处理，如果有可用优惠券，进入待支付订单
订单服务 -> 订单服务: 统计优惠金额，填充到订单信息中
订单服务 -> 订单服务: 保存历史订单和充电单价
订单服务 -> kafka: 发送订单结算消息（财务扣款和营销活动参与）
订单服务 -> 订单服务: 推送道闸
订单服务 -> 订单服务: 流量方案抽成记录
deactivate 订单服务
end

group 5、财务扣款
财务服务 -> kafka: 拉取订单结算消息
activate 订单服务
财务服务 -> 财务服务: 短信配置查询
财务服务 -> 财务服务: 占位费配置查询
财务服务 -> 财务服务: 异常冻结的金额解冻
财务服务 -> 财务服务: 企业钱包、个人钱包扣款
财务服务 -> kafka: 发送钱包扣款和占位单短信通知的消息
财务服务 -> 财务服务: 生成票务订单
deactivate 财务服务
end















@enduml
