@startuml
'https://plantuml.com/sequence-diagram
!theme toy

xxljob -> 清分服务: 执行分支核销定时任务
activate 清分服务
清分服务 -> 清分服务: 查询所有清分状态为未分账（有额度）和未分账（无额度）的清分订单
清分服务 -> 清分服务: 查询清分订单涉及电站的所有退款状态为成功，对冲状态为待对冲、进行中的退款记录, \n按退款时间升序排序
清分服务 -> 清分服务: 未分账（有额度）清分订单与退款记录对冲逻辑
清分服务 -> 清分服务: 未分账（无额度）清分订单与用户可用额度处理逻辑
清分服务 -> 清分服务: 提取所有待核销的清分订单,根据清分策略计算分账金额\n将数据写入文件上传ftp，将清分订单待核销为已提交状态。
@enduml
