@startuml
'https://plantuml.com/sequence-diagram
!theme toy

'activate 订单服务
'订单服务 -> 订单服务: 生成历史订单
'订单服务 -> kafka: 发送订单结算消息
'deactivate 订单服务
'财务服务 -> kafka: 拉取订单结算消息
'activate 财务服务
'财务服务 -> 财务服务: 用户钱包金额扣款（优先用退款金额支付）
'财务服务 -> 财务服务: 生成流水
'财务服务 -> kafka: 发送钱包扣款及订单内容消息
'deactivate 财务服务
'清分服务 -> kafka: 拉取钱包扣款及订单内容消息
'activate 清分服务
'alt 是互联互通订单
'    清分服务 -> 清分服务: 不处理
'else 不是互联互通订单
'    清分服务 -> 清分服务: 构建清分订单对象
'    清分服务 -> 清分服务: 根据钱包扣款信息填充扣款信息、实际费用、清分状态(未分账（有额度）、未分账（无额度）)
'    清分服务 -> DB: 清分订单生成
'end
'deactivate 清分服务

xxljob -> 清分服务: 调用分账定时任务
activate 清分服务
清分服务 -> 财务服务: 查询昨日充电订单、占位单支付信息\n（包含充值扣款信息、退款扣款信息、充值扣款对应支付单号信息、充电单号、占位单号）
activate 财务服务
财务服务 -> 财务服务: 查询充电订单扣款、占位单扣款信息流水
财务服务 -> 财务服务: 根据流水查询扣款钱包明细的流水类型、充值单号
财务服务 -> 财务服务: 组装数据
财务服务 --> 清分服务: 返回查询结果
deactivate 财务服务
清分服务 -> 订单服务: 根据昨日财务扣款信息中的充电单号、占位单号\n 查询充电订单、占位订单
activate 订单服务
订单服务 --> 清分服务: 返回充电订单、占位订单
deactivate 订单服务
清分服务 -> 清分服务: 构建清分充电订单、清分占位订单\n状态为未分账（有额度）、未分账（无额度）
清分服务 -> 清分服务: 保存清分充电订单、清分占位订单
清分服务 -> 清分服务: 保存订单充值扣款的信息
@enduml
