@startuml
'https://plantuml.com/sequence-diagram
!theme toy

actor 管理员

管理员 -> 充电平台: 发起充电订单退款
activate 充电平台
充电平台 -> 清分服务: 调用充电订单退款接口
activate 清分服务
清分服务 -> 清分服务: 分布式锁，控制幂等
清分服务 -> 财务服务: 调用修正退款金额接口
activate 财务服务
财务服务 -> 财务服务: 修正金额至钱包(可退款金额不能增加)
财务服务 -> 财务服务: 生成流水
财务服务 --> 清分服务: 返回成功失败
deactivate 财务服务
alt 返回失败
    清分服务 --> 清分服务: 不处理
else
    清分服务 -> 清分服务: 生成退款记录，对冲状态为待对冲
    清分服务 -> 订单服务: 修改历史订单是否退款状态标记
end
清分服务 --> 充电平台: 返回成功失败
deactivate 清分服务
充电平台 --> 管理员: 返回成功失败
@enduml
