@startuml
'https://plantuml.com/activity-diagram-beta

!theme toy

title 清分订单生命周期

start
group 定时任务2点执行

group 清分订单初始化
floating note: 未分账有额度、未分账无额度、挂起
:根据时间范围拉取所有订单的流水及扣款详情，默认昨天;
:根据扣款详情生成订单消费明细;
:根据流水中的订单号查询订单;
:过滤掉未开启清分运营商的订单;
:根据订单及扣款详情初始化清分订单;
:初始化扣负后补充消费明细的待对冲订单;
:数据入库;
:同步订单标记位已清分;
end group

group 清分订单对冲
floating note: 待核销、完全对冲、无额度
:查询未分账有额度、未分账无额度、无额度状态的清分订单;
group 未分账（有额度）与退款记录对冲
:过滤出未分账（有额度）的清分订单;
:查询未分账（有额度）清分订单的消费明细;
:查询根据电站查询可对冲的退款记录;
:对冲，生成用户额度、额度明细，修改清分订单、消费明细、退款记录;
end group
group 未分账（无额度）与用户额度对冲
:过滤出未分账（无额度）和无额度状态的清分订单;
:查询用户额度、额度明细;
:对冲，生成额度使用记录、消费明细，修改清分订单、用户额度、用户额度明细;
end group
end group

group 清分订单计算抽成
:查询所有待核销、无额度、挂起状态的清分您订单;
:根据电站和付款时间获取清分策略;
:查询消费明细;
:查询运营商及平台在银联的企业用户号;
:计算运营商、平台的线上线下抽成;
:线上抽成生成银联核销明细;
:线下抽成生成 ？;
end group
end group

group 定时任务10点执行
group 清分订单提交
floating note: 进行中
:查询所有待提交的核销明细;
:转为银联核销数据格式;
:将核销数据写入FTP;
:清分订单状态变更;
end group
end group

group 定时任务14,16,18点执行
group 清分订单核销数据回盘
floating note: 成功、失败
:查询所有需要回盘文件名称;
:读取回盘文件;
:更新订单状态;
end group
end group
stop
@enduml
