@startuml
'https://plantuml.com/activity-diagram-beta

'start
':财务接收订单结算kafka消息;
':获取流量方结算配置结算配置;
':获取运营商的结算配置;
':渠道、流量方、运营商结算逻辑;
'if (是否是平台流量方角色的充电订单?) is (是) then
'  :推送订单数据和流量方结算数据给平台服务;
'else (no)
'endif
':开票相关逻辑;
':分润方结算逻辑;
'stop

start
:根据充电订单中的电站查询电站的分润配置;
:根据分润配置查询分润周期数据;
:根据分润配置计算分润;
:保存分润记录;
:修改分润周期数据;
stop


@enduml

