@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "运营商结算配置~抽成配置" as A
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
